import type { Mood } from "./types";

const MOODS: Mood[] = [
  // ── High Energy ──────────────────────────────────────────────────────────
  {
    id: "shock",
    name: "Shock",
    group: "high_energy",
    feel: 'record scratch "Wait, WHAT?"',
    wordTemperature: [
      "explosive",
      "unprecedented",
      "shattered",
      "nobody expected",
      "just happened",
    ],
    sentenceRhythm: "Short. Fragmented. Then one long one that lands hard.",
    openingEnergy: "Opens with a brain-breaking fact — no warm-up, no context",
    punctuationStyle: "Em-dashes mid-sentence. Ellipses that cut off. Caps for impact.",
    readerExitState: "Jolted. Needs to share immediately.",
  },
  {
    id: "hype",
    name: "Hype",
    group: "high_energy",
    feel: "crowd on its feet",
    wordTemperature: [
      "game-changer",
      "massive",
      "finally",
      "THIS is it",
      "buckle up",
    ],
    sentenceRhythm: "Punchy building lines — each one bigger than the last.",
    openingEnergy: "Opens at the headline moment — no build-up, pure arrival",
    punctuationStyle: "Exclamation points earned, not scattered. Bold on key phrases.",
    readerExitState: "Electric. Wants to be part of what's happening.",
  },
  {
    id: "drama",
    name: "Drama",
    group: "high_energy",
    feel: "season finale energy",
    wordTemperature: [
      "betrayal",
      "showdown",
      "moment of truth",
      "all eyes on",
      "the stakes",
    ],
    sentenceRhythm: "Cinematic scene-setting — wide shot, then close-up.",
    openingEnergy: "Opens with characters in position, tension already coiled",
    punctuationStyle: "Long dramatic pauses via em-dashes. Short sentences at peaks.",
    readerExitState: "Gripped. Cannot look away.",
  },
  {
    id: "suspense",
    name: "Suspense",
    group: "high_energy",
    feel: "something's coming",
    wordTemperature: [
      "quietly",
      "behind the scenes",
      "sources say",
      "developing",
      "about to",
    ],
    sentenceRhythm: "Slow reveals — information rationed deliberately.",
    openingEnergy: "Opens with a hint or signal, not the full picture",
    punctuationStyle: "Trailing sentences that don't quite finish... Deliberate gaps.",
    readerExitState: "Leaning forward. Checking for updates.",
  },

  // ── Emotional ────────────────────────────────────────────────────────────
  {
    id: "fear",
    name: "Fear",
    group: "emotional",
    feel: "ground shifting underfoot",
    wordTemperature: [
      "risk",
      "exposure",
      "vulnerable",
      "ticking clock",
      "fallout",
    ],
    sentenceRhythm: "Urgent short sentences. No room for breath.",
    openingEnergy: "Opens with the threat — immediate and concrete",
    punctuationStyle: "Periods like slammed doors. No softening commas.",
    readerExitState: "Alert. Scanning for exits.",
  },
  {
    id: "hope",
    name: "Hope",
    group: "emotional",
    feel: "light at the end of the tunnel",
    wordTemperature: [
      "breakthrough",
      "turning point",
      "possibility",
      "what if this works",
      "signal",
    ],
    sentenceRhythm: "Warm, forward-looking — problem first, then the signal.",
    openingEnergy: "Opens with the problem, then pivots to the first sign of change",
    punctuationStyle: "Gentle em-dashes for possibility. Questions that open, not close.",
    readerExitState: "Cautiously optimistic. Wants to believe.",
  },
  {
    id: "nostalgia",
    name: "Nostalgia",
    group: "emotional",
    feel: '"remember when..."',
    wordTemperature: [
      "once",
      "back when",
      "the era of",
      "things were different",
      "remember",
    ],
    sentenceRhythm: "Reflective longer sentences — the kind you read slowly.",
    openingEnergy: "Opens with a vivid sensory memory, specific and warm",
    punctuationStyle: "Commas that linger. Parenthetical asides (like this one).",
    readerExitState: "Wistful. Feeling a connection to something lost.",
  },
  {
    id: "anger",
    name: "Anger",
    group: "emotional",
    feel: "righteous fire",
    wordTemperature: [
      "unacceptable",
      "accountable",
      "enough",
      "the audacity",
      "how is this",
    ],
    sentenceRhythm: "Declarative. No hedging. No passive voice.",
    openingEnergy: "Opens with the injustice — named plainly and fully",
    punctuationStyle: "Hard periods. No exclamation marks — the words carry the heat.",
    readerExitState: "Validated fury. Ready to act.",
  },

  // ── Intellectual ─────────────────────────────────────────────────────────
  {
    id: "curiosity",
    name: "Curiosity",
    group: "intellectual",
    feel: '"huh, interesting..."',
    wordTemperature: [
      "surprisingly",
      "turns out",
      "what's interesting is",
      "dig deeper",
      "but why",
    ],
    sentenceRhythm: "Question-driven — each answer spawns the next question.",
    openingEnergy: "Opens with a surprising fact that doesn't quite make sense yet",
    punctuationStyle: "Questions mid-paragraph. Em-dashes before the reveal.",
    readerExitState: "Pulled forward. Wants to know more.",
  },
  {
    id: "irony",
    name: "Irony",
    group: "intellectual",
    feel: "dry smile",
    wordTemperature: [
      "naturally",
      "predictably",
      "in a twist surprising no one",
      "as expected",
      "of course",
    ],
    sentenceRhythm: "Understated humor — the gap between what's said and what's meant.",
    openingEnergy: "Opens with a deadpan observation that rewards a second reading",
    punctuationStyle: "Minimal. Let the understatement breathe. No exclamation marks ever.",
    readerExitState: "Smart. Gets it. Quietly amused.",
  },
  {
    id: "awe",
    name: "Awe",
    group: "intellectual",
    feel: "stepping back, seeing the full scale",
    wordTemperature: [
      "scale",
      "magnitude",
      "in human history",
      "unprecedented scope",
      "perspective",
    ],
    sentenceRhythm: "Expansive, zooming out — sentence length grows with the idea.",
    openingEnergy: "Opens with a wow-fact that reframes everything that follows",
    punctuationStyle: "Long sweeping sentences. Occasional one-word paragraph. Silence.",
    readerExitState: "Perspective shift. Feels small in the best way.",
  },
  {
    id: "vindication",
    name: "Vindication",
    group: "intellectual",
    feel: '"called it"',
    wordTemperature: [
      "finally",
      "as predicted",
      "the signs were there",
      "told you so",
      "receipts",
    ],
    sentenceRhythm: "Confident past-tense references — the record is being set straight.",
    openingEnergy: "Opens with the prediction that landed, cited with quiet authority",
    punctuationStyle: "Measured. Controlled. The confidence of not needing to shout.",
    readerExitState: "Deepened trust. Feels like they're in on something.",
  },
];

export const MOOD_REGISTRY: Map<string, Mood> = new Map(
  MOODS.map((mood) => [mood.id, mood])
);

export function getMood(id: string): Mood | undefined {
  return MOOD_REGISTRY.get(id);
}
